### ISSUE TITLE
Debug assert in TrackDAO::addTracksAddTrack()

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11462]
### Bug Description

This happens to me after starting Mixxx 2.3.4 with a new library, but with a track loaded in the samplers from before: 

```
Warning [Main]: ../../src/library/dao/trackdao.cpp 415 FAILED QUERY [ "INSERT INTO track_locations (location,directory,filename,filesize,fs_deleted,needs_verification) VALUES (:location,:directory,:filename,:filesize,:fs_deleted,:needs_verification)" ] QSqlError("5", "Unable to fetch row", "database is locked") Skip inserting duplicate track location "/home/daniel/Musik/Abba - Best Of Abba/19 Abba - Angeleyes.m4a"
Critical [Main]: DEBUG ASSERT: "pTrack->getDateAdded().isValid()" in function TrackId TrackDAO::addTracksAddTrack(const TrackPointer&, bool) at ../../src/library/dao/trackdao.cpp:551
``` 

Here is the back trace:
```
#0  raise (sig=sig@entry=2) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00005555558440f4 in mixxx::(anonymous namespace)::MessageHandler(QtMsgType, QMessageLogContext const&, QString const&) (type=<optimized out>, input=...) at ../../src/util/logging.cpp:171
#2  0x00007ffff3ac31f8 in qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) (msgType=QtCriticalMsg, context=..., message="DEBUG ASSERT: \"pTrack->getDateAdded().isValid()\" in function TrackId TrackDAO::addTracksAddTrack(const TrackPointer&, bool) at ../../src/library/dao/trackdao.cpp:551") at global/qlogging.cpp:1836
#3  0x00007ffff3ac3319 in qt_message(QtMsgType, const QMessageLogContext &, const char *, typedef __va_list_tag __va_list_tag *) (msgType=QtCriticalMsg, context=..., msg=<optimized out>, ap=<optimized out>) at global/qlogging.cpp:373
#4  0x00007ffff3a926cc in QMessageLogger::critical(char const*, ...) const (this=this@entry=0x7fffffffd290, msg=msg@entry=0x5555560777e8 "%s: \"%s\" in function %s at %s:%d") at global/qlogging.cpp:767
#5  0x000055555564fe04 in mixxx_debug_assert(char const*, char const*, int, char const*) (assertion=assertion@entry=0x5555560da0d0 "pTrack->getDateAdded().isValid()", file=file@entry=0x55555611fea8 "../../src/library/dao/trackdao.cpp", line=line@entry=551, function=function@entry=0x5555561212e8 "TrackId TrackDAO::addTracksAddTrack(const TrackPointer&, bool)") at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h:91
#6  0x00005555556f0085 in TrackDAO::addTracksAddTrack(std::shared_ptr<Track> const&, bool) (this=0x55555b60df58, pTrack=std::shared_ptr<Track> (use count 2, weak count 1) = {...}, unremove=<optimized out>) at ../../src/util/db/dbid.h:115
#7  0x0000555555e96ad0 in TrackDAO::addTracksAddFile(TrackFile const&, bool) (this=0x55555b60df58, trackFile=..., unremove=<optimized out>) at ../../src/library/dao/trackdao.cpp:716
#8  0x0000555555e9a3df in TrackDAO::getOrAddTrack(TrackRef const&, bool*) (this=this@entry=0x55555b60df58, trackRef=..., pAlreadyInLibrary=pAlreadyInLibrary@entry=0x7fffffffd607) at ../../src/track/trackfile.h:33
#9  0x0000555555b5193a in TrackCollection::getOrAddTrack(TrackRef const&, bool*) (this=0x55555b60deb0, trackRef=..., pAlreadyInLibrary=pAlreadyInLibrary@entry=0x7fffffffd607) at ../../src/library/trackcollection.cpp:554
#10 0x0000555555b5caa0 in TrackCollectionManager::getOrAddTrack(TrackRef const&, bool*) const (this=0x55555b4ab660, trackRef=..., pAlreadyInLibrary=pAlreadyInLibrary@entry=0x0) at ../../src/library/trackcollectionmanager.cpp:426
#11 0x0000555555afd881 in Library::slotLoadLocationToPlayer(QString const&, QString const&) (this=0x55555b549bc0, location=..., group="[Sampler2]") at /usr/include/c++/9/bits/atomic_base.h:413
#12 0x00007ffff3cbf328 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffd7c0, r=0x55555b549bc0, this=0x55555b6d21e0) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#13 QMetaObject::activate(QObject*, int, int, void**) (sender=0x555556c37a20, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#14 0x0000555555b836b4 in PlayerManager::loadLocationToPlayer(QString const&, QString const&) (this=<optimized out>, _t1="/home/daniel/Musik/Abba - Best Of Abba/19 Abba - Angeleyes.m4a", _t2="[Sampler2]") at mixxx-lib_autogen/include/moc_playermanager.cpp:375
#15 0x0000555555b856d9 in PlayerManager::slotLoadToPlayer(QString const&, QString const&) (this=<optimized out>, location="/home/daniel/Musik/Abba - Best Of Abba/19 Abba - Angeleyes.m4a", group="[Sampler2]") at ../../src/mixer/playermanager.cpp:639
#16 0x0000555555b90465 in SamplerBank::loadSamplerBankFromPath(QString const&) (this=this@entry=0x55555a04d010, samplerBankPath="/home/daniel/.mixxx/samplers.xml") at ../../src/mixer/samplerbank.cpp:219
#17 0x0000555555b85059 in PlayerManager::loadSamplers() (this=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h:313
#18 0x000055555573be61 in MixxxMainWindow::initialize(QApplication*, CmdlineArgs const&) (this=<optimized out>, pApp=<optimized out>, args=...) at ../../src/mixxx.cpp:678
#19 0x000055555573d5e4 in MixxxMainWindow::MixxxMainWindow(QApplication*, CmdlineArgs const&) (this=0x7fffffffddc0, pApp=0x7fffffffdd80, args=...) at ../../src/mixxx.cpp:273
#20 0x000055555570ab00 in (anonymous namespace)::runMixxx (args=..., app=0x7fffffffdd80) at ../../src/main.cpp:112
#21 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../../src/main.cpp:112 



### Version

2.3.4

### OS

Linux

**Comment by ronso0** [comment]
Duplicate of #16179 (and the meta issue #6631?) ?
