### ISSUE TITLE
DEBUG ASSERT: "outputChannelStates.size() == 0" in function void EffectProcessorImpl<EffectSpecificState>::initializeInputChannel"

### ISSUE THREAD

**Issue by Swiftb0y** [mixxxdj/mixxx#11808]
### Bug Description

Not sure when I have time to investigate (or whether this has been reported already), but lets track it before I we forget.
<details><summary>Backtrace</summary>
<p>

```cpp
Thread 1 (Thread 0x7fffea492280 (LWP 199435) "mixxx"):
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff2cb08b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff2c5fabe in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff2c4887f in __GI_abort () at abort.c:79
#4  0x00007ffff32b1898 in qt_message_fatal (message=Python Exception <class 'gdb.error'>: value has been optimized out
<synthetic pointer>, context=<optimized out>) at global/qlogging.cpp:1914
#5  QMessageLogger::fatal(char const*, ...) const (this=this@entry=0x7fffffffd010, msg=msg@entry=0x55eda8 "%s") at global/qlogging.cpp:893
#6  0x0000000000cf488c in mixxx::(anonymous namespace)::handleMessage(QtMsgType, QMessageLogContext const&, QString const&) (type=QtCriticalMsg, context=..., input="DEBUG ASSERT: \"outputChannelStates.size() == 0\" in function void EffectProcessorImpl<EffectSpecificState>::initializeInputChannel(ChannelHandle, const mixxx::EngineParameters&) [with EffectSpecificSta"...) at /home/swiftb0y/Sourcerepositories/mixxx/src/util/logging.cpp:355
#7  0x00007ffff32ed028 in qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) (msgType=msgType@entry=QtCriticalMsg, context=..., message="DEBUG ASSERT: \"outputChannelStates.size() == 0\" in function void EffectProcessorImpl<EffectSpecificState>::initializeInputChannel(ChannelHandle, const mixxx::EngineParameters&) [with EffectSpecificSta"...) at global/qlogging.cpp:1843
#8  0x00007ffff32ed14e in qt_message(QtMsgType, const QMessageLogContext &, const char *, typedef __va_list_tag __va_list_tag *) (msgType=msgType@entry=QtCriticalMsg, context=..., msg=msg@entry=0x59a718 "%s: \"%s\" in function %s at %s:%d", ap=ap@entry=0x7fffffffd100) at global/qlogging.cpp:378
#9  0x00007ffff32b145b in QMessageLogger::critical(char const*, ...) const (this=this@entry=0x7fffffffd200, msg=msg@entry=0x59a718 "%s: \"%s\" in function %s at %s:%d") at global/qlogging.cpp:772
#10 0x00000000005bb785 in mixxx_debug_assert(char const*, char const*, int, char const*) (assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at /home/swiftb0y/Sourcerepositories/mixxx/src/util/assert.h:9
#11 0x000000000077250a in EffectProcessorImpl<PitchShiftGroupState>::initializeInputChannel(ChannelHandle, mixxx::EngineParameters const&) (this=0xf366f00, inputChannel=..., engineParameters=...) at /home/swiftb0y/Sourcerepositories/mixxx/src/effects/backends/effectprocessor.h:205
#12 0x000000000081147b in EngineEffect::initalizeInputChannel(ChannelHandle) (this=0xf37c7e0, inputChannel=...) at /home/swiftb0y/Sourcerepositories/mixxx/src/engine/effects/engineeffect.cpp:65
#13 0x00000000006d1be1 in EffectSlot::initalizeInputChannel(ChannelHandle) (this=<optimized out>, inputChannel=...) at /home/swiftb0y/Sourcerepositories/mixxx/src/effects/effectslot.cpp:199
#14 0x00000000006cb217 in EffectChain::enableForInputChannel(ChannelHandleAndGroup const&) (this=0x4bc18b0, handleGroup=...) at /home/swiftb0y/Sourcerepositories/mixxx/src/engine/channelhandle.h:107
#15 0x00007ffff34ded0b in QObject::event(QEvent*) (this=0x4bc18b0, e=0x7fff140d6850) at kernel/qobject.cpp:1347
#16 0x00007ffff63aeb75 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x4bc18b0, e=0x7fff140d6850) at kernel/qapplication.cpp:3640
#17 0x00007ffff34b4188 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x4bc18b0, event=0x7fff140d6850) at kernel/qcoreapplication.cpp:1064
#18 0x00007ffff34b43a2 in QCoreApplication::sendEvent(QObject*, QEvent*) (receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1462
#19 0x00007ffff34b7635 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x115ea90) at kernel/qcoreapplication.cpp:1821
#20 0x00007ffff34b78ed in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=<optimized out>, event_type=<optimized out>) at kernel/qcoreapplication.cpp:1680
#21 0x00007ffff3506c3f in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x1194c10) at kernel/qeventdispatcher_glib.cpp:277
#22 0x00007ffff581248c in g_main_dispatch (context=0x7fffd8000ee0) at ../glib/gmain.c:3460
#23 g_main_context_dispatch (context=0x7fffd8000ee0) at ../glib/gmain.c:4200
#24 0x00007ffff5870648 in g_main_context_iterate.isra.0 (context=0x7fffd8000ee0, block=1, dispatch=1, self=<optimized out>) at ../glib/gmain.c:4276
#25 0x00007ffff580fb13 in g_main_context_iteration (context=0x7fffd8000ee0, may_block=1) at ../glib/gmain.c:4343
#26 0x00007ffff3506729 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x11b4bb0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#27 0x00007ffff34b2b4b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffd740, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#28 0x00007ffff34baddb in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#29 0x00007ffff5b60edd in QGuiApplication::exec() () at kernel/qguiapplication.cpp:1863
#30 0x00007ffff63aeae9 in QApplication::exec() () at kernel/qapplication.cpp:2832
#31 0x00000000005b719c in (anonymous namespace)::runMixxx (args=<optimized out>, pApp=0x7fffffffd800) at /home/swiftb0y/Sourcerepositories/mixxx/src/main.cpp:82
#32 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/swiftb0y/Sourcerepositories/mixxx/src/main.cpp:213

```

</p>
</details> 

### Version

2.4 beta

### OS

Linux Fedora 38

**Comment by daschuer** [comment]
Fixed in https://github.com/mixxxdj/mixxx/pull/11809
